### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by mcre** [rago1975/atena-sashikomi#1]
@rago1975
このリポジトリを参考に私の方でも差し込み印刷のリポジトリを作成したいのですが、

* ライセンスを明記

もしくは

* 私にこのリポジトリのソースコードを利用したMITライセンスのリポジトリを作成することの許可

をいただくことはできませんでしょうか？

**Comment by rago1975** [comment]
MITライセンスのリポジトリを作成することについては、許可します。

**Comment by mcre** [comment]
ありがとうございます。
下記リポジトリにて使用させていただきました。
https://github.com/mcre/address-printing-on-jp-postcards
